title: "Alex-min's tech blog"
description: "We design and develop the fast, open, and privacy-respecting replacement for Windows and macOS"
permalink: /:title/
theme-color: "#64baff"
gravatar: fcd81f0d7784b4eaebe0c845eed08eaf

author: Alex-Min

authors:
  alex-min:
    name: Alex-Min
    description: "Software Enthusiast"
    gravatar: fcd81f0d7784b4eaebe0c845eed08eaf
  anonymous:
    name: "Unknown Author"
    gravatar: fcd81f0d7784b4eaebe0c845eed08eaf

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
paginate_path: "/archive/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]
