title: "Alex-min's tech blog"
description: "We design and develop the fast, open, and privacy-respecting replacement for Windows and macOS"
permalink: /:title/
theme-color: "#64baff"
gravatar: eaa3cc978770998ea2bd4382935bf0f4

facebook: elementaryos
mastodon: elementary
reddit: elementaryos
twitter: elementary

authors:
  alex-min:
    name: Alex-Min
    description: "Full-Stack Engineer"
    gravatar: ac2ee6a8aeed69ab159f1f0c548a1992
  anonymous:
    name: "Unknown Author"
    gravatar: ac2ee6a8aeed69ab159f1f0c548a1992

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
paginate_path: "/archive/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]
